name: Playwright Tests
on:
  push:
    branches: [ci]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and push docker image
        run: |
          docker login -t -u ${{ secrets.DOCKER_USER }} --password-stdin ${{ secrets.DOCKER_PASSWORD }}
          docker build -t jackiesoft/demo-app:playwright-js
          docker push docker.io jackiesoft/demo-app:playwright-js
