name: Playwright Tests
on:
  push:
    branches: [ci]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and push docker image
        env:
          docker_username: ${{ secrets.DOCKER_USER }}
          docker_password: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo Build and push docker image
          docker login --username $docker_username --password-stdin $docker_password
          docker build -t jackiesoft/demo-app:playwright-js
          docker push docker.io jackiesoft/demo-app:playwright-js
